"""new fields in user model

Revision ID: 54172c945a3b
Revises: 7c38defec4c7
Create Date: 2018-12-02 11:37:14.094887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54172c945a3b'
down_revision = '7c38defec4c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
