"""history table

Revision ID: 852983f2df42
Revises: c1797a0a330f
Create Date: 2018-12-03 13:26:00.613764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852983f2df42'
down_revision = 'c1797a0a330f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('author', sa.String(length=140), nullable=True),
    sa.Column('pages', sa.String(length=40), nullable=True),
    sa.Column('cost', sa.String(length=60), nullable=True),
    sa.Column('type', sa.BOOLEAN(), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_author'), 'history', ['author'], unique=False)
    op.create_index(op.f('ix_history_cost'), 'history', ['cost'], unique=False)
    op.create_index(op.f('ix_history_pages'), 'history', ['pages'], unique=False)
    op.create_index(op.f('ix_history_time_stamp'), 'history', ['time_stamp'], unique=False)
    op.create_index(op.f('ix_history_title'), 'history', ['title'], unique=False)
    op.create_index(op.f('ix_history_type'), 'history', ['type'], unique=False)
    op.add_column(u'books', sa.Column('status', sa.BOOLEAN(), nullable=True))
    op.create_index(op.f('ix_books_status'), 'books', ['status'], unique=False)
    op.add_column(u'user', sa.Column('points', sa.String(length=140), nullable=True))
    op.create_index(op.f('ix_user_points'), 'user', ['points'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_points'), table_name='user')
    op.drop_column(u'user', 'points')
    op.drop_index(op.f('ix_books_status'), table_name='books')
    op.drop_column(u'books', 'status')
    op.drop_index(op.f('ix_history_type'), table_name='history')
    op.drop_index(op.f('ix_history_title'), table_name='history')
    op.drop_index(op.f('ix_history_time_stamp'), table_name='history')
    op.drop_index(op.f('ix_history_pages'), table_name='history')
    op.drop_index(op.f('ix_history_cost'), table_name='history')
    op.drop_index(op.f('ix_history_author'), table_name='history')
    op.drop_table('history')
    # ### end Alembic commands ###
