"""books table

Revision ID: c1797a0a330f
Revises: 54172c945a3b
Create Date: 2018-12-02 19:17:36.193584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1797a0a330f'
down_revision = '54172c945a3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('author', sa.String(length=140), nullable=True),
    sa.Column('pages', sa.String(length=40), nullable=True),
    sa.Column('cost', sa.String(length=60), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_author'), 'books', ['author'], unique=False)
    op.create_index(op.f('ix_books_cost'), 'books', ['cost'], unique=False)
    op.create_index(op.f('ix_books_pages'), 'books', ['pages'], unique=False)
    op.create_index(op.f('ix_books_time_stamp'), 'books', ['time_stamp'], unique=False)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_time_stamp'), table_name='books')
    op.drop_index(op.f('ix_books_pages'), table_name='books')
    op.drop_index(op.f('ix_books_cost'), table_name='books')
    op.drop_index(op.f('ix_books_author'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
